/**
 * Walks a manifest backwards through history and turns what it finds into
 * candidate decisions.
 *
 * A single pass yields both signals worth having: an add with no prior trace is
 * an origination, and an add paired with a remove is a replacement — the
 * strongest signal there is, because reversal only happens when the first
 * option actually hurt.
 */
import {
  commitStats,
  countImportingFiles,
  logForPath,
  repoFacts,
  rootShas,
  showFile,
  type Commit,
  type CommitStats,
  type Repo,
} from '../git/index.js';
import { alternativesTo, categoryOf, isNonDecision } from './catalog.js';
import { diffManifests, parseManifest, type Dep, type Manifest } from './manifest.js';

export type CandidateKind = 'replacement' | 'origination' | 'removal';

export interface TestResult {
  pass: boolean;
  why: string;
}

export interface Candidate {
  kind: CandidateKind;
  packageName: string;
  subjectKey: string;
  displaced: string | null;
  category: string | null;
  categoryLabel: string | null;

  sha: string;
  shortSha: string;
  date: Date;
  subject: string;
  authorEmail: string;

  filesInCommit: number;
  projectAgeDays: number;
  introducedAlone: boolean;
  looksScaffoldGenerated: boolean;
  importingFiles: number;

  tests: {
    alternative: TestResult;
    loadBearing: TestResult;
    deliberate: TestResult;
  };
}

export interface DetectOptions {
  /** Defaults to `package.json`; a path so monorepos are not a rewrite later. */
  manifestPath?: string;
  /** How many commits a removal may lag its replacement by. */
  replacementWindow?: number;
}

export interface DetectResult {
  candidates: Candidate[];
  commitsWalked: number;
  manifestPath: string;
}

interface Observation {
  index: number;
  commit: Commit;
  dep: Dep;
}

const DEFAULTS = { manifestPath: 'package.json', replacementWindow: 3 } as const;

/** A commit large enough that nothing in it was individually considered. */
const SCAFFOLD_FILE_COUNT = 50;
/** Manifest, lockfile, and maybe one source file. */
const ALONE_FILE_COUNT = 4;

const SCAFFOLD_SUBJECT =
  /^\s*(initial commit|init|initial|scaffold|bootstrap|first commit|create[- ]\w+[- ]app|generated by)/i;

export async function detectDependencyDecisions(
  repo: Repo,
  options: DetectOptions = {},
): Promise<DetectResult> {
  const manifestPath = options.manifestPath ?? DEFAULTS.manifestPath;
  const window = options.replacementWindow ?? DEFAULTS.replacementWindow;

  const [facts, roots, commits] = await Promise.all([
    repoFacts(repo),
    rootShas(repo),
    logForPath(repo, manifestPath),
  ]);

  // --- 1. Walk the manifest, collecting raw adds and removes -----------------
  const adds: Observation[] = [];
  const removes: Observation[] = [];
  let previous: Manifest | null = null;

  for (const [index, commit] of commits.entries()) {
    const source = await showFile(repo, commit.sha, manifestPath);
    const manifest = parseManifest(source);
    // A malformed revision is skipped without advancing `previous`, so the next
    // good revision diffs against the last good one rather than against null —
    // which would otherwise report every dependency as newly added.
    if (manifest === null) continue;

    const diff = diffManifests(previous, manifest);
    for (const dep of diff.added) adds.push({ index, commit, dep });
    for (const dep of diff.removed) removes.push({ index, commit, dep });
    previous = manifest;
  }

  // --- 2. Pair removes with adds into replacements ---------------------------
  const consumed = new Set<Observation>();
  const pairs = new Map<Observation, Observation>();

  for (const add of adds) {
    const addCategory = categoryOf(add.dep.name);
    if (addCategory === null) continue;

    const match = removes
      .filter(
        (remove) =>
          !consumed.has(remove) &&
          remove.index <= add.index &&
          add.index - remove.index <= window &&
          categoryOf(remove.dep.name)?.slug === addCategory.slug,
      )
      // Same-commit swaps are unambiguous; prefer them over a lagging removal.
      .sort((a, b) => b.index - a.index)[0];

    if (match !== undefined) {
      consumed.add(match);
      pairs.set(add, match);
    }
  }

  // --- 3. Build candidates ---------------------------------------------------
  const statsCache = new Map<string, CommitStats>();
  const statsFor = async (sha: string): Promise<CommitStats> => {
    const cached = statsCache.get(sha);
    if (cached !== undefined) return cached;
    const stats = await commitStats(repo, sha);
    statsCache.set(sha, stats);
    return stats;
  };

  const importCache = new Map<string, number>();
  const importsFor = async (name: string): Promise<number> => {
    const cached = importCache.get(name);
    if (cached !== undefined) return cached;
    const count = await countImportingFiles(repo, name);
    importCache.set(name, count);
    return count;
  };

  const candidates: Candidate[] = [];

  for (const add of adds) {
    if (isNonDecision(add.dep.name)) continue;
    const displaced = pairs.get(add);
    candidates.push(
      await buildCandidate({
        kind: displaced === undefined ? 'origination' : 'replacement',
        dep: add.dep,
        displaced: displaced?.dep.name ?? null,
        commit: add.commit,
        stats: await statsFor(add.commit.sha),
        importingFiles: await importsFor(add.dep.name),
        firstCommitAt: facts.firstCommitAt,
        isRoot: roots.has(add.commit.sha),
      }),
    );
  }

  // A removal nobody replaced is its own signal: something stopped being worth
  // its cost, and that is exactly the kind of thing worth asking about.
  for (const remove of removes) {
    if (consumed.has(remove) || isNonDecision(remove.dep.name)) continue;
    candidates.push(
      await buildCandidate({
        kind: 'removal',
        dep: remove.dep,
        displaced: null,
        commit: remove.commit,
        stats: await statsFor(remove.commit.sha),
        importingFiles: 0,
        firstCommitAt: facts.firstCommitAt,
        isRoot: roots.has(remove.commit.sha),
      }),
    );
  }

  return { candidates, commitsWalked: commits.length, manifestPath };
}

interface BuildInput {
  kind: CandidateKind;
  dep: Dep;
  displaced: string | null;
  commit: Commit;
  stats: CommitStats;
  importingFiles: number;
  firstCommitAt: Date;
  isRoot: boolean;
}

async function buildCandidate(input: BuildInput): Promise<Candidate> {
  const { kind, dep, displaced, commit, stats, importingFiles, isRoot } = input;

  const category = categoryOf(dep.name);
  const projectAgeDays = Math.max(
    0,
    Math.round(
      (commit.authoredAt.getTime() - input.firstCommitAt.getTime()) / 86_400_000,
    ),
  );

  const looksScaffoldGenerated =
    isRoot ||
    stats.filesChanged > SCAFFOLD_FILE_COUNT ||
    SCAFFOLD_SUBJECT.test(commit.subject);

  const introducedAlone = stats.filesChanged > 0 && stats.filesChanged <= ALONE_FILE_COUNT;

  return {
    kind,
    packageName: dep.name,
    subjectKey: `npm:${dep.name}`,
    displaced,
    category: category?.slug ?? null,
    categoryLabel: category?.label ?? null,

    sha: commit.sha,
    shortSha: commit.sha.slice(0, 7),
    date: commit.authoredAt,
    subject: commit.subject,
    authorEmail: commit.authorEmail,

    filesInCommit: stats.filesChanged,
    projectAgeDays,
    introducedAlone,
    looksScaffoldGenerated,
    importingFiles,

    tests: {
      alternative: testAlternative(kind, dep.name, displaced),
      loadBearing: testLoadBearing(kind, dep, importingFiles),
      deliberate: testDeliberate({
        kind,
        looksScaffoldGenerated,
        introducedAlone,
        projectAgeDays,
        isRoot,
        filesChanged: stats.filesChanged,
      }),
    },
  };
}

/** Test 1: there was a real alternative. */
function testAlternative(
  kind: CandidateKind,
  packageName: string,
  displaced: string | null,
): TestResult {
  if (kind === 'replacement' && displaced !== null) {
    return { pass: true, why: `displaced ${displaced}` };
  }
  const category = categoryOf(packageName);
  if (category === null) {
    return { pass: false, why: 'no known alternatives in the catalogue' };
  }
  const others = alternativesTo(packageName).slice(0, 3).join(', ');
  return { pass: true, why: `${category.label} — also ${others}` };
}

/** Test 2: it is load-bearing. */
function testLoadBearing(
  kind: CandidateKind,
  dep: Dep,
  importingFiles: number,
): TestResult {
  if (kind === 'removal') {
    return { pass: true, why: 'removed outright — something stopped being worth it' };
  }
  if (importingFiles > 0) {
    return {
      pass: true,
      why: `imported in ${importingFiles} file${importingFiles === 1 ? '' : 's'}`,
    };
  }
  if (dep.kind === 'dev') {
    return { pass: false, why: 'dev dependency with no imports at HEAD' };
  }
  return { pass: false, why: 'not imported anywhere at HEAD' };
}

interface DeliberateInput {
  kind: CandidateKind;
  looksScaffoldGenerated: boolean;
  introducedAlone: boolean;
  projectAgeDays: number;
  isRoot: boolean;
  filesChanged: number;
}

/**
 * Test 3: they actually chose it. The most important filter, and the easiest to
 * get wrong — everything here is answerable from the introducing diff alone.
 */
function testDeliberate(input: DeliberateInput): TestResult {
  if (input.isRoot) {
    return { pass: false, why: 'arrived in the repo’s first commit' };
  }

  // A replacement cannot arrive by accident: something had to be removed for it.
  // The commit-size veto below exists to catch dependencies that rode along in
  // generated output, and generators originate — they never swap. Applying it
  // to replacements threw away real router and build-transform swaps that
  // happened to land in a busy commit.
  if (input.kind === 'replacement') {
    return {
      pass: true,
      why: input.introducedAlone
        ? `swap landed alone, ${input.projectAgeDays} days into the project`
        : `swap among ${input.filesChanged} changed files, ${input.projectAgeDays} days in`,
    };
  }

  if (input.filesChanged > SCAFFOLD_FILE_COUNT) {
    return { pass: false, why: `landed among ${input.filesChanged} changed files` };
  }
  if (input.looksScaffoldGenerated) {
    return { pass: false, why: 'commit looks scaffold-generated' };
  }
  if (input.introducedAlone) {
    return {
      pass: true,
      why: `landed alone, ${input.projectAgeDays} days into the project`,
    };
  }
  return {
    pass: true,
    why: `${input.filesChanged} files, ${input.projectAgeDays} days into the project`,
  };
}
